name: Echidna

on: [push, pull_request]

jobs:
  echidna:
    name: Echidna
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        testName:
          - DssVestMintableEchidnaTest
          - DssVestSuckableEchidnaTest
          - DssVestTransferrableEchidnaTest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache Echidna Corpus
        uses: actions/cache@v2
        with:
          path: corpus
          key: abi-${{ hashFiles('**/crytic-export/combined_solc.json') }}

      - name: Echidna Testing
        uses: crytic/echidna-action@v1
        with:
          files: echidna/${{ matrix.testName }}.sol
          contract: ${{ matrix.testName }}
          config: echidna.config.ci.yml
          corpus-dir: corpus
          solc-version: 0.6.12
