name: Echidna

on: [push, pull_request]

jobs:
  echidna:
    name: Echidna
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        testName:
          - DssVestMintableEchidnaTest
          - DssVestSuckableEchidnaTest
          - DssVestTransferrableEchidnaTest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install crytic-compile
        run: pip3 install crytic-compile

      - name: Install solc-select
        run: pip3 install solc-select

      - name: Solc Select 0.6.12
        run: solc-select install 0.6.12

      - name: Crytic Compile
        run: crytic-compile echidna/${( matrix.testName )}.sol --solc-solcs-select 0.6.12 --export-format solc

      - name: Cache Echidna Corpus
        uses: actions/cache@v2
        with:
          path: corpus
          key: abi-${{ hashFiles('**/crytic-export/combined_solc.json') }}

      - name: Echidna Testing
        uses: crytic/echidna-action@v1
        with:
          files: echidna/${{ matrix.testName }}.sol
          contract: ${{ matrix.testName }}
          config: echidna.config.ci.yml
          corpus-dir: corpus
          solc-version: 0.6.12
